[package]
name = "codegen_optimizer"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1"
walkdir = "2"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
log = "0.4"
simple_logger = "1.16"
